//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5_TylerNowakCodyThompson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string ID { get; set; }
        public string BEGIN_YEARMONTH { get; set; }
        public string BEGIN_DAY { get; set; }
        public string BEGIN_TIME { get; set; }
        public string END_YEARMONTH { get; set; }
        public string END_DAY { get; set; }
        public string END_TIME { get; set; }
        public string EPISODE_ID { get; set; }
        public string EVENT_ID { get; set; }
        public string STATE { get; set; }
        public string STATE_FIPS { get; set; }
        public string YEAR { get; set; }
        public string MONTH_NAME { get; set; }
        public string EVENT_TYPE { get; set; }
        public string CZ_TYPE { get; set; }
        public string CZ_FIPS { get; set; }
        public string CZ_NAME { get; set; }
        public string WFO { get; set; }
        public string BEGIN_DATE_TIME { get; set; }
        public string CZ_TIMEZONE { get; set; }
        public string END_DATE_TIME { get; set; }
        public string INJURIES_DIRECT { get; set; }
        public string INJURIES_INDIRECT { get; set; }
        public string DEATHS_DIRECT { get; set; }
        public string DEATHS_INDIRECT { get; set; }
        public string DAMAGE_PROPERTY { get; set; }
        public string DAMAGE_CROPS { get; set; }
        public string SOURCE { get; set; }
        public string MAGNITUDE { get; set; }
        public string MAGNITUDE_TYPE { get; set; }
        public string FLOOD_CAUSE { get; set; }
        public string CATEGORY { get; set; }
        public string TOR_F_SCALE { get; set; }
        public string TOR_LENGTH { get; set; }
        public string TOR_WIDTH { get; set; }
        public string TOR_OTHER_WFO { get; set; }
        public string TOR_OTHER_CZ_STATE { get; set; }
        public string TOR_OTHER_CZ_FIPS { get; set; }
        public string TOR_OTHER_CZ_NAME { get; set; }
        public string BEGIN_RANGE { get; set; }
        public string BEGIN_AZIMUTH { get; set; }
        public string BEGIN_LOCATION { get; set; }
        public string END_RANGE { get; set; }
        public string END_AZIMUTH { get; set; }
        public string END_LOCATION { get; set; }
        public string BEGIN_LAT { get; set; }
        public string BEGIN_LON { get; set; }
        public string END_LAT { get; set; }
        public string END_LON { get; set; }
        public string DATA_SOURCE { get; set; }
    }
}
